module: Amplify
author: Amazon Web Services
github_url: https://github.com/aws-amplify/amplify-swift

exclude:
  - Pods

clean: true
skip_undocumented: false
undocumented_text: ""
hide_documentation_coverage: true
sdk: iphone
theme: apple
build_tool_arguments:
  - -workspace
  - Amplify.xcworkspace
  - -scheme
  - Amplify

docset_icon: readme-images/amplify-icon.png

