module: Amplify
author: Amazon Web Services
github_url: https://github.com/aws-amplify/amplify-swift

swift-build-tool: spm
clean: true
skip_undocumented: false
undocumented_text: ""
hide_documentation_coverage: true
sdk: iphone
theme: apple
build_tool_arguments:
  - -Xswiftc
  - -swift-version
  - -Xswiftc
  - "5"

docset_icon: readme-images/amplify-icon.png