# Do not specify an `included` section at this top-level file. Specify the
# `--config` option pointing to this file, and the `--path` option to the files
# you wish to lint
included:
  - Amplify
  - AmplifyPlugins

excluded:
  - Pods
  - .build
  - AmplifyAsyncTesting
  - AmplifyFunctionalTests
  - AmplifyTestApp
  - AmplifyTestCommon
  - AmplifyTests
  - AmplifyPlugins/Core/AWSPluginsCoreTests
  - AmplifyPlugins/Core/AWSPluginsTestCommon
  - AmplifyPlugins/Notifications/Push/Tests
  - AmplifyPlugins/*/Tests

analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - empty_count

# configurable rules can be customized from this configuration file
closing_brace: error
colon:
  severity: error
comma: error
empty_count: 
  severity: warning
empty_enum_arguments: error
function_body_length:
  warning: 150 
  error: 150
identifier_name:
  excluded:
    - id
    - of
    - or
line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  warning: 160
  error: 160
opening_brace:
  severity: error
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
non_optional_string_data_conversion: 
  severity: error