included:
  - AWSAPICategoryPlugin
  - AWSAPICategoryPluginTests
  - AWSAPICategoryPluginIntegrationTests

analyzer_rules:
  - unused_import
  - unused_private_declaration

opt_in_rules:
  - empty_count

# configurable rules can be customized from this configuration file
closing_brace: error
colon:
  severity: error
comma: error
empty_count: warning
empty_enum_arguments: error
function_body_length:
  warning: 100
  error: 150
line_length:
  warning: 120
  error: 160
opening_brace: error
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
