load '../../build-support/dependencies.rb'

platform :ios, '11.0'
use_frameworks!

include_build_tools!

target 'AWSAPICategoryPlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "AppSyncRealTimeClient", "~> 3.1"

  target "AWSAPICategoryPluginTests" do
    inherit! :complete
    
    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  include_test_utilities!
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'

  target "AWSAPICategoryPluginTestCommon" do
    inherit! :complete

    target "AWSAPICategoryPluginFunctionalTests" do
      inherit! :complete
    end 
  
    target "GraphQLWithIAMIntegrationTests" do 
      pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
      inherit! :complete
    end
  
    target "GraphQLWithUserPoolIntegrationTests" do 
      pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
      inherit! :complete
    end
    
    target "GraphQLWithLambdaAuthIntegrationTests" do
      pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
      inherit! :complete
    end
  
    target "RESTWithIAMIntegrationTests" do 
      pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
      inherit! :complete
    end

    target "RESTWithUserPoolIntegrationTests" do 
      pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
      inherit! :complete
    end
  end
end
