platform :ios, '11.0'
use_frameworks!

AWS_SDK_VERSION = "2.13.0"

pod 'SwiftFormat/CLI'
pod 'SwiftLint'

target 'AWSAPICategoryPlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "ReachabilitySwift", "~> 5.0.0"
  pod "AppSyncRealTimeClient", "~> 1.1.0"

  target "AWSAPICategoryPluginTests" do
    inherit! :complete
    
    pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
    pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
    pod 'AmplifyTestCommon', :path => '../../'
    pod "ReachabilitySwift", "~> 5.0.0"
  end
end

target "HostApp" do
  use_frameworks!
  pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
  pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'

  target "AWSAPICategoryPluginTestCommon" do
    inherit! :complete

    target "AWSAPICategoryPluginFunctionalTests" do
      inherit! :complete
    end 
  
    target "GraphQLWithIAMIntegrationTests" do 
      inherit! :complete
    end
  
    target "GraphQLWithUserPoolIntegrationTests" do 
      inherit! :complete
    end
  
    target "RESTWithIAMIntegrationTests" do 
      inherit! :complete
    end

    target "RESTWithUserPoolIntegrationTests" do 
      inherit! :complete
    end
  end
end
