platform :ios, '12.0'
use_frameworks!

AWS_SDK_VERSION = "2.12.0"

pod 'SwiftFormat/CLI'
pod 'SwiftLint'

target 'AWSAPICategoryPlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "Starscream", "~> 3.0.2"
end

target "HostApp" do
  use_frameworks!
  pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
  pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
  pod 'AmplifyTestCommon', :path => '../../'

  target "AWSAPICategoryPluginIntegrationTests" do
    inherit! :complete
  end

  target "AWSAPICategoryPluginTests" do
    inherit! :complete
  end
end