load '../../build-support/dependencies.rb'

platform :ios, '12.0'
use_frameworks!

include_build_tools!

target 'AWSCognitoAuthPlugin' do
  pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "AWSMobileClient", $OPTIMISTIC_AWS_SDK_VERSION

  target "AWSCognitoAuthPluginTests" do
    inherit! :complete

    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  include_test_utilities!
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'

  target "AWSCognitoAuthPluginIntegrationTests" do
    inherit! :complete
  end
end
