name: 'Run xcodebuild test'
description: 'Action runs the test for the scheme specified'

inputs:
  scheme:
    required: true
    type: string
  destination:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Test ${{ inputs.scheme }}
      run: |
        xcodebuild test -scheme AWSCognitoAuthPlugin -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}        
      shell: bash 