name: 'Run xcodebuild test'
description: 'Action runs the test for the scheme specified'

inputs:
  scheme:
    required: true
    type: string
  project_path:
    required: false
    type: string
  xcode_path:
    required: false
    type: string
  destination:
    required: false
    type: string
    default: 'platform=iOS Simulator,name=iPhone 13,OS=latest'
  sdk:
    required: false
    type: string
    default: 'iphonesimulator'
  other_flags:
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Test ${{ inputs.scheme }}
      env:
        SCHEME: ${{ inputs.scheme }}
        PROJECT_PATH: ${{ inputs.project_path }}
        XCODE_PATH: ${{ inputs.xcode_path }}
      run: |
        cd $PROJECT_PATH
        sudo xcode-select -s /Applications/Xcode_14.3.app
        xcodebuild -version
        xcodebuild test -scheme $SCHEME -sdk '${{ inputs.sdk }}' -destination '${{ inputs.destination }}' ${{ inputs.other_flags }} | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}
      shell: bash
