# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppSyncSubscriptionClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppSyncSubscriptionClient
  pod "Starscream", "~> 3.0.2"

  target 'AppSyncSubscriptionClientTests' do
    # Pods for testing
  end

end
