load '../build-support/dependencies.rb'

platform :ios, "13.0"
use_frameworks!

include_build_tools!

target "AmplifyCombineSupport" do
  pod 'Amplify', :path => '../'

  target "AmplifyCombineSupportTests" do
    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../'
  end

end
