# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

default_platform(:ios)

pods = [
  "Amplify.podspec",
  "AWSPluginsCore.podspec",
  "CoreMLPredictionsPlugin.podspec",
  "AWSPredictionsPlugin.podspec",
  "AmplifyPlugins.podspec"
]

platform :ios do
  desc "Release pods"
  lane :release_pods do

    pods.each { |pod|
      pod_push(path: pod, allow_warnings: true, swift_version: "5.1")
      Actions.sh('pod repo update')
    }

  end

  desc "Generate docs"
  lane :generate_docs do
    sh("jazzy --output='/Users/distiller/amplify-ios/docs' --min-acl=internal -x -workspace,/Users/distiller/amplify-ios/Amplify.xcworkspace,-scheme,Amplify")
    commit_push()
  end

  desc "Commit and push"
  private_lane :commit_push do
    sh("git config --global user.email $GITHUB_EMAIL")
    sh("git config --global user.name $GITHUB_USER")

    sh("git add /Users/distiller/amplify-ios/docs/")
    commit_message = "docs: update API docs [skip ci]"
    sh("git commit -m '#{commit_message}'")
    sh("git push --set-upstream origin gh-pages")
    sh("git push origin")
  end
end
