load '../../build-support/dependencies.rb'

platform :ios, '12.0'
use_frameworks!

include_build_tools!

target 'AWSS3StoragePlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "AWSS3", $OPTIMISTIC_AWS_SDK_VERSION

  target "AWSS3StoragePluginTests" do
    inherit! :complete

    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  include_test_utilities!
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'

  target "AWSS3StoragePluginFunctionalTests" do
    inherit! :complete
  end
end
