platform :ios, '12.0'
use_frameworks!

AWS_SDK_VERSION = "2.12.5"

pod 'SwiftFormat/CLI'
pod 'SwiftLint'

target 'AWSS3StoragePlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "AWSS3", "~> #{AWS_SDK_VERSION}"

  target "AWSS3StoragePluginTests" do
    inherit! :complete

    pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
    pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
    pod 'AmplifyTestCommon', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
  pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "AWSMobileClient", "~> #{AWS_SDK_VERSION}"

  target "AWSS3StoragePluginFunctionalTests" do
    inherit! :complete
  end
end
