platform :ios, '11.0'
use_frameworks!

AWS_SDK_VERSION = "2.13.0"

pod 'SwiftFormat/CLI'
pod 'SwiftLint'

target 'AWSDataStoreCategoryPlugin' do
	pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "SQLite.swift", "~> 0.12.0"

  target "AWSDataStoreCategoryPluginTests" do
    inherit! :complete
    
    pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
    pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
    pod 'AmplifyTestCommon', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  pod "CwlPreconditionTesting", :git => "https://github.com/mattgallagher/CwlPreconditionTesting.git", :tag => "1.2.0"
  pod "CwlCatchException", :git => "https://github.com/mattgallagher/CwlCatchException.git", :tag => "1.2.0"
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'
  pod "AWSMobileClient", "~> #{AWS_SDK_VERSION}"

  target "AWSDataStoreCategoryPluginIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
  end
end