load '../../build-support/dependencies.rb'

platform :ios, '11.0'
use_frameworks!

include_build_tools!

target 'AWSDataStoreCategoryPlugin' do
  pod 'Amplify', :path => '../../'
  pod 'AWSPluginsCore', :path => '../../'
  pod "SQLite.swift", "0.13.2"
  pod "AppSyncRealTimeClient", :path => "~/aws-amplify/aws-appsync-realtime-client-ios/"
  target "AWSDataStoreCategoryPluginTests" do
    inherit! :complete
    
    include_test_utilities!
    pod 'AmplifyTestCommon', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
  end
end

target "HostApp" do
  use_frameworks!
  include_test_utilities!
  pod 'AmplifyTestCommon', :path => '../../'
  pod 'Amplify', :path => '../../'
  pod "AWSMobileClient", $OPTIMISTIC_AWS_SDK_VERSION

  target "AWSDataStoreCategoryPluginIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
  end

  target "AWSDataStoreCategoryPluginAuthIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
  end

  target "AWSDataStoreCategoryPluginFlutterIntegrationTests" do
    inherit! :complete

    pod 'AmplifyPlugins/AWSAPIPlugin', :path => '../../'
    pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'
  end
end