name: 'Checkout'
description: 'checkout repository'

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
