load '../../build-support/dependencies.rb'

platform :ios, '13.0'
use_frameworks!

include_build_tools!

target 'AWSLocationGeoPlugin' do
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    pod "AWSLocation", $OPTIMISTIC_AWS_SDK_VERSION
end

target "HostApp" do
    use_frameworks!
    include_test_utilities!

    pod 'AmplifyTestCommon', :path => '../../'
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    
    target "AWSLocationGeoPluginIntegrationTests" do
        pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'

        inherit! :complete
    end

    target "AWSLocationGeoPluginTests" do
        inherit! :complete
    end
end
