name: 'Download test configuration'
description: 'Action downloads the test configuration from the specified folder'

inputs:
  resource_subfolder:
    required: true
    type: string
  aws_role_to_assume:
    required: true
    type: string
  aws_region:
    required: true
    type: string
  aws_s3_bucket:
    required: true
    type: string
  destination:
    required: false
    type: string
    default: '~/.aws-amplify/amplify-ios/testconfiguration/'

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials for {{ inputs.resource_subfolder }}
      uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # Pin to 1.6.1
      with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: IntegrationRoleSessions
          role-duration-seconds: 900

    - name: Copy configuration for {{ inputs.resource_subfolder }}
      run: | 
        aws s3 cp ${{ inputs.aws_s3_bucket }}/${{ inputs.resource_subfolder }}/ ${{ inputs.destination }} --recursive
      shell: bash
