//
// Copyright Amazon.com Inc. or its affiliates.
// All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by smithy-swift-codegen. DO NOT EDIT!

@_spi(SmithyReadWrite) import ClientRuntime
import Foundation
import class SmithyHTTPAPI.HTTPResponse
@_spi(SmithyReadWrite) import class SmithyJSON.Reader
@_spi(SmithyReadWrite) import class SmithyJSON.Writer
import enum ClientRuntime.ErrorFault
import enum SmithyReadWrite.ReaderError
@_spi(SmithyReadWrite) import enum SmithyReadWrite.ReadingClosures
@_spi(SmithyReadWrite) import enum SmithyReadWrite.WritingClosures
@_spi(SmithyTimestamps) import enum SmithyTimestamps.TimestampFormat
import protocol AWSClientRuntime.AWSServiceError
import protocol ClientRuntime.HTTPError
import protocol ClientRuntime.ModeledError
@_spi(SmithyReadWrite) import protocol SmithyReadWrite.SmithyReader
@_spi(SmithyReadWrite) import protocol SmithyReadWrite.SmithyWriter
@_spi(SmithyReadWrite) import struct AWSClientRuntime.RestJSONError
@_spi(UnknownAWSHTTPServiceError) import struct AWSClientRuntime.UnknownAWSHTTPServiceError
@_spi(SmithyReadWrite) import struct SmithyReadWrite.ReadingClosureBox
@_spi(SmithyReadWrite) import struct SmithyReadWrite.WritingClosureBox

/// An unexpected error occurred.
public struct InternalServerException: ClientRuntime.ModeledError, AWSClientRuntime.AWSServiceError, ClientRuntime.HTTPError, Swift.Error {

    public struct Properties {
        /// This member is required.
        public internal(set) var message: Swift.String? = nil
    }

    public internal(set) var properties = Properties()
    public static var typeName: Swift.String { "InternalServerException" }
    public static var fault: ClientRuntime.ErrorFault { .server }
    public static var isRetryable: Swift.Bool { false }
    public static var isThrottling: Swift.Bool { false }
    public internal(set) var httpResponse = SmithyHTTPAPI.HTTPResponse()
    public internal(set) var message: Swift.String?
    public internal(set) var requestID: Swift.String?

    public init(
        message: Swift.String? = nil
    )
    {
        self.properties.message = message
    }
}

/// The specified resource was not found.
public struct ResourceNotFoundException: ClientRuntime.ModeledError, AWSClientRuntime.AWSServiceError, ClientRuntime.HTTPError, Swift.Error {

    public struct Properties {
        /// This member is required.
        public internal(set) var message: Swift.String? = nil
    }

    public internal(set) var properties = Properties()
    public static var typeName: Swift.String { "ResourceNotFoundException" }
    public static var fault: ClientRuntime.ErrorFault { .client }
    public static var isRetryable: Swift.Bool { false }
    public static var isThrottling: Swift.Bool { false }
    public internal(set) var httpResponse = SmithyHTTPAPI.HTTPResponse()
    public internal(set) var message: Swift.String?
    public internal(set) var requestID: Swift.String?

    public init(
        message: Swift.String? = nil
    )
    {
        self.properties.message = message
    }
}

/// A service quota has been exceeded.
public struct ServiceQuotaExceededException: ClientRuntime.ModeledError, AWSClientRuntime.AWSServiceError, ClientRuntime.HTTPError, Swift.Error {

    public struct Properties {
        /// This member is required.
        public internal(set) var message: Swift.String? = nil
    }

    public internal(set) var properties = Properties()
    public static var typeName: Swift.String { "ServiceQuotaExceededException" }
    public static var fault: ClientRuntime.ErrorFault { .client }
    public static var isRetryable: Swift.Bool { false }
    public static var isThrottling: Swift.Bool { false }
    public internal(set) var httpResponse = SmithyHTTPAPI.HTTPResponse()
    public internal(set) var message: Swift.String?
    public internal(set) var requestID: Swift.String?

    public init(
        message: Swift.String? = nil
    )
    {
        self.properties.message = message
    }
}

/// One of the input parameters is not valid.
public struct ValidationException: ClientRuntime.ModeledError, AWSClientRuntime.AWSServiceError, ClientRuntime.HTTPError, Swift.Error {

    public struct Properties {
        /// This member is required.
        public internal(set) var message: Swift.String? = nil
    }

    public internal(set) var properties = Properties()
    public static var typeName: Swift.String { "ValidationException" }
    public static var fault: ClientRuntime.ErrorFault { .client }
    public static var isRetryable: Swift.Bool { false }
    public static var isThrottling: Swift.Bool { false }
    public internal(set) var httpResponse = SmithyHTTPAPI.HTTPResponse()
    public internal(set) var message: Swift.String?
    public internal(set) var requestID: Swift.String?

    public init(
        message: Swift.String? = nil
    )
    {
        self.properties.message = message
    }
}

public struct CreateSavingsPlanInput: Swift.Sendable {
    /// A unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
    public var clientToken: Swift.String?
    /// The hourly commitment, in the same currency of the savingsPlanOfferingId. This is a value between 0.001 and 1 million. You cannot specify more than five digits after the decimal point.
    /// This member is required.
    public var commitment: Swift.String?
    /// The purchase time of the Savings Plan in UTC format (YYYY-MM-DDTHH:MM:SSZ).
    public var purchaseTime: Foundation.Date?
    /// The ID of the offering.
    /// This member is required.
    public var savingsPlanOfferingId: Swift.String?
    /// One or more tags.
    public var tags: [Swift.String: Swift.String]?
    /// The up-front payment amount. This is a whole number between 50 and 99 percent of the total value of the Savings Plan. This parameter is only supported if the payment option is Partial Upfront.
    public var upfrontPaymentAmount: Swift.String?

    public init(
        clientToken: Swift.String? = nil,
        commitment: Swift.String? = nil,
        purchaseTime: Foundation.Date? = nil,
        savingsPlanOfferingId: Swift.String? = nil,
        tags: [Swift.String: Swift.String]? = nil,
        upfrontPaymentAmount: Swift.String? = nil
    )
    {
        self.clientToken = clientToken
        self.commitment = commitment
        self.purchaseTime = purchaseTime
        self.savingsPlanOfferingId = savingsPlanOfferingId
        self.tags = tags
        self.upfrontPaymentAmount = upfrontPaymentAmount
    }
}

public struct CreateSavingsPlanOutput: Swift.Sendable {
    /// The ID of the Savings Plan.
    public var savingsPlanId: Swift.String?

    public init(
        savingsPlanId: Swift.String? = nil
    )
    {
        self.savingsPlanId = savingsPlanId
    }
}

public struct DeleteQueuedSavingsPlanInput: Swift.Sendable {
    /// The ID of the Savings Plan.
    /// This member is required.
    public var savingsPlanId: Swift.String?

    public init(
        savingsPlanId: Swift.String? = nil
    )
    {
        self.savingsPlanId = savingsPlanId
    }
}

public struct DeleteQueuedSavingsPlanOutput: Swift.Sendable {

    public init() { }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanRateFilterName: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case instanceType
        case operation
        case productDescription
        case productType
        case region
        case serviceCode
        case tenancy
        case usageType
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanRateFilterName] {
            return [
                .instanceType,
                .operation,
                .productDescription,
                .productType,
                .region,
                .serviceCode,
                .tenancy,
                .usageType
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .instanceType: return "instanceType"
            case .operation: return "operation"
            case .productDescription: return "productDescription"
            case .productType: return "productType"
            case .region: return "region"
            case .serviceCode: return "serviceCode"
            case .tenancy: return "tenancy"
            case .usageType: return "usageType"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan rate filter.
    public struct SavingsPlanRateFilter: Swift.Sendable {
        /// The filter name.
        public var name: SavingsplansClientTypes.SavingsPlanRateFilterName?
        /// The filter values.
        public var values: [Swift.String]?

        public init(
            name: SavingsplansClientTypes.SavingsPlanRateFilterName? = nil,
            values: [Swift.String]? = nil
        )
        {
            self.name = name
            self.values = values
        }
    }
}

public struct DescribeSavingsPlanRatesInput: Swift.Sendable {
    /// The filters.
    public var filters: [SavingsplansClientTypes.SavingsPlanRateFilter]?
    /// The maximum number of results to return with a single call. To retrieve additional results, make another call with the returned token value.
    public var maxResults: Swift.Int?
    /// The token for the next page of results.
    public var nextToken: Swift.String?
    /// The ID of the Savings Plan.
    /// This member is required.
    public var savingsPlanId: Swift.String?

    public init(
        filters: [SavingsplansClientTypes.SavingsPlanRateFilter]? = nil,
        maxResults: Swift.Int? = nil,
        nextToken: Swift.String? = nil,
        savingsPlanId: Swift.String? = nil
    )
    {
        self.filters = filters
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.savingsPlanId = savingsPlanId
    }
}

extension SavingsplansClientTypes {

    public enum CurrencyCode: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case cny
        case usd
        case sdkUnknown(Swift.String)

        public static var allCases: [CurrencyCode] {
            return [
                .cny,
                .usd
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .cny: return "CNY"
            case .usd: return "USD"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanProductType: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case ec2
        case fargate
        case lambda
        case sagemaker
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanProductType] {
            return [
                .ec2,
                .fargate,
                .lambda,
                .sagemaker
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .ec2: return "EC2"
            case .fargate: return "Fargate"
            case .lambda: return "Lambda"
            case .sagemaker: return "SageMaker"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanRatePropertyKey: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case instanceFamily
        case instanceType
        case productDescription
        case region
        case tenancy
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanRatePropertyKey] {
            return [
                .instanceFamily,
                .instanceType,
                .productDescription,
                .region,
                .tenancy
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .instanceFamily: return "instanceFamily"
            case .instanceType: return "instanceType"
            case .productDescription: return "productDescription"
            case .region: return "region"
            case .tenancy: return "tenancy"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan rate property.
    public struct SavingsPlanRateProperty: Swift.Sendable {
        /// The property name.
        public var name: SavingsplansClientTypes.SavingsPlanRatePropertyKey?
        /// The property value.
        public var value: Swift.String?

        public init(
            name: SavingsplansClientTypes.SavingsPlanRatePropertyKey? = nil,
            value: Swift.String? = nil
        )
        {
            self.name = name
            self.value = value
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanRateServiceCode: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case ec2
        case fargate
        case fargateEks
        case lambda
        case sagemaker
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanRateServiceCode] {
            return [
                .ec2,
                .fargate,
                .fargateEks,
                .lambda,
                .sagemaker
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .ec2: return "AmazonEC2"
            case .fargate: return "AmazonECS"
            case .fargateEks: return "AmazonEKS"
            case .lambda: return "AWSLambda"
            case .sagemaker: return "AmazonSageMaker"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanRateUnit: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case hours
        case lambdaGbSecond
        case request
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanRateUnit] {
            return [
                .hours,
                .lambdaGbSecond,
                .request
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .hours: return "Hrs"
            case .lambdaGbSecond: return "Lambda-GB-Second"
            case .request: return "Request"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan rate.
    public struct SavingsPlanRate: Swift.Sendable {
        /// The currency.
        public var currency: SavingsplansClientTypes.CurrencyCode?
        /// The specific Amazon Web Services operation for the line item in the billing report.
        public var operation: Swift.String?
        /// The product type.
        public var productType: SavingsplansClientTypes.SavingsPlanProductType?
        /// The properties.
        public var properties: [SavingsplansClientTypes.SavingsPlanRateProperty]?
        /// The rate.
        public var rate: Swift.String?
        /// The service.
        public var serviceCode: SavingsplansClientTypes.SavingsPlanRateServiceCode?
        /// The unit.
        public var unit: SavingsplansClientTypes.SavingsPlanRateUnit?
        /// The usage details of the line item in the billing report.
        public var usageType: Swift.String?

        public init(
            currency: SavingsplansClientTypes.CurrencyCode? = nil,
            operation: Swift.String? = nil,
            productType: SavingsplansClientTypes.SavingsPlanProductType? = nil,
            properties: [SavingsplansClientTypes.SavingsPlanRateProperty]? = nil,
            rate: Swift.String? = nil,
            serviceCode: SavingsplansClientTypes.SavingsPlanRateServiceCode? = nil,
            unit: SavingsplansClientTypes.SavingsPlanRateUnit? = nil,
            usageType: Swift.String? = nil
        )
        {
            self.currency = currency
            self.operation = operation
            self.productType = productType
            self.properties = properties
            self.rate = rate
            self.serviceCode = serviceCode
            self.unit = unit
            self.usageType = usageType
        }
    }
}

public struct DescribeSavingsPlanRatesOutput: Swift.Sendable {
    /// The token to use to retrieve the next page of results. This value is null when there are no more results to return.
    public var nextToken: Swift.String?
    /// The ID of the Savings Plan.
    public var savingsPlanId: Swift.String?
    /// Information about the Savings Plan rates.
    public var searchResults: [SavingsplansClientTypes.SavingsPlanRate]?

    public init(
        nextToken: Swift.String? = nil,
        savingsPlanId: Swift.String? = nil,
        searchResults: [SavingsplansClientTypes.SavingsPlanRate]? = nil
    )
    {
        self.nextToken = nextToken
        self.savingsPlanId = savingsPlanId
        self.searchResults = searchResults
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlansFilterName: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case commitment
        case ec2InstanceFamily
        case end
        case paymentOption
        case region
        case savingsPlanType
        case start
        case term
        case upfront
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlansFilterName] {
            return [
                .commitment,
                .ec2InstanceFamily,
                .end,
                .paymentOption,
                .region,
                .savingsPlanType,
                .start,
                .term,
                .upfront
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .commitment: return "commitment"
            case .ec2InstanceFamily: return "ec2-instance-family"
            case .end: return "end"
            case .paymentOption: return "payment-option"
            case .region: return "region"
            case .savingsPlanType: return "savings-plan-type"
            case .start: return "start"
            case .term: return "term"
            case .upfront: return "upfront"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan filter.
    public struct SavingsPlanFilter: Swift.Sendable {
        /// The filter name.
        public var name: SavingsplansClientTypes.SavingsPlansFilterName?
        /// The filter value.
        public var values: [Swift.String]?

        public init(
            name: SavingsplansClientTypes.SavingsPlansFilterName? = nil,
            values: [Swift.String]? = nil
        )
        {
            self.name = name
            self.values = values
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanState: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case active
        case paymentFailed
        case paymentPending
        case pendingReturn
        case queued
        case queuedDeleted
        case retired
        case returned
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanState] {
            return [
                .active,
                .paymentFailed,
                .paymentPending,
                .pendingReturn,
                .queued,
                .queuedDeleted,
                .retired,
                .returned
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .active: return "active"
            case .paymentFailed: return "payment-failed"
            case .paymentPending: return "payment-pending"
            case .pendingReturn: return "pending-return"
            case .queued: return "queued"
            case .queuedDeleted: return "queued-deleted"
            case .retired: return "retired"
            case .returned: return "returned"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

public struct DescribeSavingsPlansInput: Swift.Sendable {
    /// The filters.
    public var filters: [SavingsplansClientTypes.SavingsPlanFilter]?
    /// The maximum number of results to return with a single call. To retrieve additional results, make another call with the returned token value.
    public var maxResults: Swift.Int?
    /// The token for the next page of results.
    public var nextToken: Swift.String?
    /// The Amazon Resource Names (ARN) of the Savings Plans.
    public var savingsPlanArns: [Swift.String]?
    /// The IDs of the Savings Plans.
    public var savingsPlanIds: [Swift.String]?
    /// The current states of the Savings Plans.
    public var states: [SavingsplansClientTypes.SavingsPlanState]?

    public init(
        filters: [SavingsplansClientTypes.SavingsPlanFilter]? = nil,
        maxResults: Swift.Int? = nil,
        nextToken: Swift.String? = nil,
        savingsPlanArns: [Swift.String]? = nil,
        savingsPlanIds: [Swift.String]? = nil,
        states: [SavingsplansClientTypes.SavingsPlanState]? = nil
    )
    {
        self.filters = filters
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.savingsPlanArns = savingsPlanArns
        self.savingsPlanIds = savingsPlanIds
        self.states = states
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanPaymentOption: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case allUpfront
        case noUpfront
        case partialUpfront
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanPaymentOption] {
            return [
                .allUpfront,
                .noUpfront,
                .partialUpfront
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .allUpfront: return "All Upfront"
            case .noUpfront: return "No Upfront"
            case .partialUpfront: return "Partial Upfront"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanType: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case compute
        case ec2Instance
        case sagemaker
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanType] {
            return [
                .compute,
                .ec2Instance,
                .sagemaker
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .compute: return "Compute"
            case .ec2Instance: return "EC2Instance"
            case .sagemaker: return "SageMaker"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan.
    public struct SavingsPlan: Swift.Sendable {
        /// The hourly commitment amount in the specified currency.
        public var commitment: Swift.String?
        /// The currency.
        public var currency: SavingsplansClientTypes.CurrencyCode?
        /// The description.
        public var description: Swift.String?
        /// The EC2 instance family.
        public var ec2InstanceFamily: Swift.String?
        /// The end time.
        public var end: Swift.String?
        /// The ID of the offering.
        public var offeringId: Swift.String?
        /// The payment option.
        public var paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption?
        /// The product types.
        public var productTypes: [SavingsplansClientTypes.SavingsPlanProductType]?
        /// The recurring payment amount.
        public var recurringPaymentAmount: Swift.String?
        /// The Amazon Web Services Region.
        public var region: Swift.String?
        /// The time until when a return for the Savings Plan can be requested. If the Savings Plan is not returnable, the field reflects the Savings Plan start time.
        public var returnableUntil: Swift.String?
        /// The Amazon Resource Name (ARN) of the Savings Plan.
        public var savingsPlanArn: Swift.String?
        /// The ID of the Savings Plan.
        public var savingsPlanId: Swift.String?
        /// The plan type.
        public var savingsPlanType: SavingsplansClientTypes.SavingsPlanType?
        /// The start time.
        public var start: Swift.String?
        /// The current state.
        public var state: SavingsplansClientTypes.SavingsPlanState?
        /// One or more tags.
        public var tags: [Swift.String: Swift.String]?
        /// The duration of the term, in seconds.
        public var termDurationInSeconds: Swift.Int
        /// The up-front payment amount.
        public var upfrontPaymentAmount: Swift.String?

        public init(
            commitment: Swift.String? = nil,
            currency: SavingsplansClientTypes.CurrencyCode? = nil,
            description: Swift.String? = nil,
            ec2InstanceFamily: Swift.String? = nil,
            end: Swift.String? = nil,
            offeringId: Swift.String? = nil,
            paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption? = nil,
            productTypes: [SavingsplansClientTypes.SavingsPlanProductType]? = nil,
            recurringPaymentAmount: Swift.String? = nil,
            region: Swift.String? = nil,
            returnableUntil: Swift.String? = nil,
            savingsPlanArn: Swift.String? = nil,
            savingsPlanId: Swift.String? = nil,
            savingsPlanType: SavingsplansClientTypes.SavingsPlanType? = nil,
            start: Swift.String? = nil,
            state: SavingsplansClientTypes.SavingsPlanState? = nil,
            tags: [Swift.String: Swift.String]? = nil,
            termDurationInSeconds: Swift.Int = 0,
            upfrontPaymentAmount: Swift.String? = nil
        )
        {
            self.commitment = commitment
            self.currency = currency
            self.description = description
            self.ec2InstanceFamily = ec2InstanceFamily
            self.end = end
            self.offeringId = offeringId
            self.paymentOption = paymentOption
            self.productTypes = productTypes
            self.recurringPaymentAmount = recurringPaymentAmount
            self.region = region
            self.returnableUntil = returnableUntil
            self.savingsPlanArn = savingsPlanArn
            self.savingsPlanId = savingsPlanId
            self.savingsPlanType = savingsPlanType
            self.start = start
            self.state = state
            self.tags = tags
            self.termDurationInSeconds = termDurationInSeconds
            self.upfrontPaymentAmount = upfrontPaymentAmount
        }
    }
}

public struct DescribeSavingsPlansOutput: Swift.Sendable {
    /// The token to use to retrieve the next page of results. This value is null when there are no more results to return.
    public var nextToken: Swift.String?
    /// Information about the Savings Plans.
    public var savingsPlans: [SavingsplansClientTypes.SavingsPlan]?

    public init(
        nextToken: Swift.String? = nil,
        savingsPlans: [SavingsplansClientTypes.SavingsPlan]? = nil
    )
    {
        self.nextToken = nextToken
        self.savingsPlans = savingsPlans
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanRateFilterAttribute: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case instanceFamily
        case instanceType
        case productDescription
        case productId
        case region
        case tenancy
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanRateFilterAttribute] {
            return [
                .instanceFamily,
                .instanceType,
                .productDescription,
                .productId,
                .region,
                .tenancy
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .instanceFamily: return "instanceFamily"
            case .instanceType: return "instanceType"
            case .productDescription: return "productDescription"
            case .productId: return "productId"
            case .region: return "region"
            case .tenancy: return "tenancy"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering rate filter.
    public struct SavingsPlanOfferingRateFilterElement: Swift.Sendable {
        /// The filter name.
        public var name: SavingsplansClientTypes.SavingsPlanRateFilterAttribute?
        /// The filter values.
        public var values: [Swift.String]?

        public init(
            name: SavingsplansClientTypes.SavingsPlanRateFilterAttribute? = nil,
            values: [Swift.String]? = nil
        )
        {
            self.name = name
            self.values = values
        }
    }
}

public struct DescribeSavingsPlansOfferingRatesInput: Swift.Sendable {
    /// The filters.
    public var filters: [SavingsplansClientTypes.SavingsPlanOfferingRateFilterElement]?
    /// The maximum number of results to return with a single call. To retrieve additional results, make another call with the returned token value.
    public var maxResults: Swift.Int?
    /// The token for the next page of results.
    public var nextToken: Swift.String?
    /// The specific Amazon Web Services operation for the line item in the billing report.
    public var operations: [Swift.String]?
    /// The Amazon Web Services products.
    public var products: [SavingsplansClientTypes.SavingsPlanProductType]?
    /// The IDs of the offerings.
    public var savingsPlanOfferingIds: [Swift.String]?
    /// The payment options.
    public var savingsPlanPaymentOptions: [SavingsplansClientTypes.SavingsPlanPaymentOption]?
    /// The plan types.
    public var savingsPlanTypes: [SavingsplansClientTypes.SavingsPlanType]?
    /// The services.
    public var serviceCodes: [SavingsplansClientTypes.SavingsPlanRateServiceCode]?
    /// The usage details of the line item in the billing report.
    public var usageTypes: [Swift.String]?

    public init(
        filters: [SavingsplansClientTypes.SavingsPlanOfferingRateFilterElement]? = nil,
        maxResults: Swift.Int? = 0,
        nextToken: Swift.String? = nil,
        operations: [Swift.String]? = nil,
        products: [SavingsplansClientTypes.SavingsPlanProductType]? = nil,
        savingsPlanOfferingIds: [Swift.String]? = nil,
        savingsPlanPaymentOptions: [SavingsplansClientTypes.SavingsPlanPaymentOption]? = nil,
        savingsPlanTypes: [SavingsplansClientTypes.SavingsPlanType]? = nil,
        serviceCodes: [SavingsplansClientTypes.SavingsPlanRateServiceCode]? = nil,
        usageTypes: [Swift.String]? = nil
    )
    {
        self.filters = filters
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.operations = operations
        self.products = products
        self.savingsPlanOfferingIds = savingsPlanOfferingIds
        self.savingsPlanPaymentOptions = savingsPlanPaymentOptions
        self.savingsPlanTypes = savingsPlanTypes
        self.serviceCodes = serviceCodes
        self.usageTypes = usageTypes
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering rate property.
    public struct SavingsPlanOfferingRateProperty: Swift.Sendable {
        /// The property name.
        public var name: Swift.String?
        /// The property value.
        public var value: Swift.String?

        public init(
            name: Swift.String? = nil,
            value: Swift.String? = nil
        )
        {
            self.name = name
            self.value = value
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering.
    public struct ParentSavingsPlanOffering: Swift.Sendable {
        /// The currency.
        public var currency: SavingsplansClientTypes.CurrencyCode?
        /// The duration, in seconds.
        public var durationSeconds: Swift.Int
        /// The ID of the offering.
        public var offeringId: Swift.String?
        /// The payment option.
        public var paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption?
        /// The description.
        public var planDescription: Swift.String?
        /// The plan type.
        public var planType: SavingsplansClientTypes.SavingsPlanType?

        public init(
            currency: SavingsplansClientTypes.CurrencyCode? = nil,
            durationSeconds: Swift.Int = 0,
            offeringId: Swift.String? = nil,
            paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption? = nil,
            planDescription: Swift.String? = nil,
            planType: SavingsplansClientTypes.SavingsPlanType? = nil
        )
        {
            self.currency = currency
            self.durationSeconds = durationSeconds
            self.offeringId = offeringId
            self.paymentOption = paymentOption
            self.planDescription = planDescription
            self.planType = planType
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering rate.
    public struct SavingsPlanOfferingRate: Swift.Sendable {
        /// The specific Amazon Web Services operation for the line item in the billing report.
        public var operation: Swift.String?
        /// The product type.
        public var productType: SavingsplansClientTypes.SavingsPlanProductType?
        /// The properties.
        public var properties: [SavingsplansClientTypes.SavingsPlanOfferingRateProperty]?
        /// The Savings Plan rate.
        public var rate: Swift.String?
        /// The Savings Plan offering.
        public var savingsPlanOffering: SavingsplansClientTypes.ParentSavingsPlanOffering?
        /// The service.
        public var serviceCode: SavingsplansClientTypes.SavingsPlanRateServiceCode?
        /// The unit.
        public var unit: SavingsplansClientTypes.SavingsPlanRateUnit?
        /// The usage details of the line item in the billing report.
        public var usageType: Swift.String?

        public init(
            operation: Swift.String? = nil,
            productType: SavingsplansClientTypes.SavingsPlanProductType? = nil,
            properties: [SavingsplansClientTypes.SavingsPlanOfferingRateProperty]? = nil,
            rate: Swift.String? = nil,
            savingsPlanOffering: SavingsplansClientTypes.ParentSavingsPlanOffering? = nil,
            serviceCode: SavingsplansClientTypes.SavingsPlanRateServiceCode? = nil,
            unit: SavingsplansClientTypes.SavingsPlanRateUnit? = nil,
            usageType: Swift.String? = nil
        )
        {
            self.operation = operation
            self.productType = productType
            self.properties = properties
            self.rate = rate
            self.savingsPlanOffering = savingsPlanOffering
            self.serviceCode = serviceCode
            self.unit = unit
            self.usageType = usageType
        }
    }
}

public struct DescribeSavingsPlansOfferingRatesOutput: Swift.Sendable {
    /// The token to use to retrieve the next page of results. This value is null when there are no more results to return.
    public var nextToken: Swift.String?
    /// Information about the Savings Plans offering rates.
    public var searchResults: [SavingsplansClientTypes.SavingsPlanOfferingRate]?

    public init(
        nextToken: Swift.String? = nil,
        searchResults: [SavingsplansClientTypes.SavingsPlanOfferingRate]? = nil
    )
    {
        self.nextToken = nextToken
        self.searchResults = searchResults
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanOfferingFilterAttribute: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case instancefamily
        case region
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanOfferingFilterAttribute] {
            return [
                .instancefamily,
                .region
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .instancefamily: return "instanceFamily"
            case .region: return "region"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering filter.
    public struct SavingsPlanOfferingFilterElement: Swift.Sendable {
        /// The filter name.
        public var name: SavingsplansClientTypes.SavingsPlanOfferingFilterAttribute?
        /// The filter values.
        public var values: [Swift.String]?

        public init(
            name: SavingsplansClientTypes.SavingsPlanOfferingFilterAttribute? = nil,
            values: [Swift.String]? = nil
        )
        {
            self.name = name
            self.values = values
        }
    }
}

public struct DescribeSavingsPlansOfferingsInput: Swift.Sendable {
    /// The currencies.
    public var currencies: [SavingsplansClientTypes.CurrencyCode]?
    /// The descriptions.
    public var descriptions: [Swift.String]?
    /// The duration, in seconds.
    public var durations: [Swift.Int]?
    /// The filters.
    public var filters: [SavingsplansClientTypes.SavingsPlanOfferingFilterElement]?
    /// The maximum number of results to return with a single call. To retrieve additional results, make another call with the returned token value.
    public var maxResults: Swift.Int?
    /// The token for the next page of results.
    public var nextToken: Swift.String?
    /// The IDs of the offerings.
    public var offeringIds: [Swift.String]?
    /// The specific Amazon Web Services operation for the line item in the billing report.
    public var operations: [Swift.String]?
    /// The payment options.
    public var paymentOptions: [SavingsplansClientTypes.SavingsPlanPaymentOption]?
    /// The plan types.
    public var planTypes: [SavingsplansClientTypes.SavingsPlanType]?
    /// The product type.
    public var productType: SavingsplansClientTypes.SavingsPlanProductType?
    /// The services.
    public var serviceCodes: [Swift.String]?
    /// The usage details of the line item in the billing report.
    public var usageTypes: [Swift.String]?

    public init(
        currencies: [SavingsplansClientTypes.CurrencyCode]? = nil,
        descriptions: [Swift.String]? = nil,
        durations: [Swift.Int]? = nil,
        filters: [SavingsplansClientTypes.SavingsPlanOfferingFilterElement]? = nil,
        maxResults: Swift.Int? = 0,
        nextToken: Swift.String? = nil,
        offeringIds: [Swift.String]? = nil,
        operations: [Swift.String]? = nil,
        paymentOptions: [SavingsplansClientTypes.SavingsPlanPaymentOption]? = nil,
        planTypes: [SavingsplansClientTypes.SavingsPlanType]? = nil,
        productType: SavingsplansClientTypes.SavingsPlanProductType? = nil,
        serviceCodes: [Swift.String]? = nil,
        usageTypes: [Swift.String]? = nil
    )
    {
        self.currencies = currencies
        self.descriptions = descriptions
        self.durations = durations
        self.filters = filters
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.offeringIds = offeringIds
        self.operations = operations
        self.paymentOptions = paymentOptions
        self.planTypes = planTypes
        self.productType = productType
        self.serviceCodes = serviceCodes
        self.usageTypes = usageTypes
    }
}

extension SavingsplansClientTypes {

    public enum SavingsPlanOfferingPropertyKey: Swift.Sendable, Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Hashable {
        case instanceFamily
        case region
        case sdkUnknown(Swift.String)

        public static var allCases: [SavingsPlanOfferingPropertyKey] {
            return [
                .instanceFamily,
                .region
            ]
        }

        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }

        public var rawValue: Swift.String {
            switch self {
            case .instanceFamily: return "instanceFamily"
            case .region: return "region"
            case let .sdkUnknown(s): return s
            }
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering property.
    public struct SavingsPlanOfferingProperty: Swift.Sendable {
        /// The property name.
        public var name: SavingsplansClientTypes.SavingsPlanOfferingPropertyKey?
        /// The property value.
        public var value: Swift.String?

        public init(
            name: SavingsplansClientTypes.SavingsPlanOfferingPropertyKey? = nil,
            value: Swift.String? = nil
        )
        {
            self.name = name
            self.value = value
        }
    }
}

extension SavingsplansClientTypes {

    /// Information about a Savings Plan offering.
    public struct SavingsPlanOffering: Swift.Sendable {
        /// The currency.
        public var currency: SavingsplansClientTypes.CurrencyCode?
        /// The description.
        public var description: Swift.String?
        /// The duration, in seconds.
        public var durationSeconds: Swift.Int
        /// The ID of the offering.
        public var offeringId: Swift.String?
        /// The specific Amazon Web Services operation for the line item in the billing report.
        public var operation: Swift.String?
        /// The payment option.
        public var paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption?
        /// The plan type.
        public var planType: SavingsplansClientTypes.SavingsPlanType?
        /// The product type.
        public var productTypes: [SavingsplansClientTypes.SavingsPlanProductType]?
        /// The properties.
        public var properties: [SavingsplansClientTypes.SavingsPlanOfferingProperty]?
        /// The service.
        public var serviceCode: Swift.String?
        /// The usage details of the line item in the billing report.
        public var usageType: Swift.String?

        public init(
            currency: SavingsplansClientTypes.CurrencyCode? = nil,
            description: Swift.String? = nil,
            durationSeconds: Swift.Int = 0,
            offeringId: Swift.String? = nil,
            operation: Swift.String? = nil,
            paymentOption: SavingsplansClientTypes.SavingsPlanPaymentOption? = nil,
            planType: SavingsplansClientTypes.SavingsPlanType? = nil,
            productTypes: [SavingsplansClientTypes.SavingsPlanProductType]? = nil,
            properties: [SavingsplansClientTypes.SavingsPlanOfferingProperty]? = nil,
            serviceCode: Swift.String? = nil,
            usageType: Swift.String? = nil
        )
        {
            self.currency = currency
            self.description = description
            self.durationSeconds = durationSeconds
            self.offeringId = offeringId
            self.operation = operation
            self.paymentOption = paymentOption
            self.planType = planType
            self.productTypes = productTypes
            self.properties = properties
            self.serviceCode = serviceCode
            self.usageType = usageType
        }
    }
}

public struct DescribeSavingsPlansOfferingsOutput: Swift.Sendable {
    /// The token to use to retrieve the next page of results. This value is null when there are no more results to return.
    public var nextToken: Swift.String?
    /// Information about the Savings Plans offerings.
    public var searchResults: [SavingsplansClientTypes.SavingsPlanOffering]?

    public init(
        nextToken: Swift.String? = nil,
        searchResults: [SavingsplansClientTypes.SavingsPlanOffering]? = nil
    )
    {
        self.nextToken = nextToken
        self.searchResults = searchResults
    }
}

public struct ListTagsForResourceInput: Swift.Sendable {
    /// The Amazon Resource Name (ARN) of the resource.
    /// This member is required.
    public var resourceArn: Swift.String?

    public init(
        resourceArn: Swift.String? = nil
    )
    {
        self.resourceArn = resourceArn
    }
}

public struct ListTagsForResourceOutput: Swift.Sendable {
    /// Information about the tags.
    public var tags: [Swift.String: Swift.String]?

    public init(
        tags: [Swift.String: Swift.String]? = nil
    )
    {
        self.tags = tags
    }
}

public struct ReturnSavingsPlanInput: Swift.Sendable {
    /// A unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
    public var clientToken: Swift.String?
    /// The ID of the Savings Plan.
    /// This member is required.
    public var savingsPlanId: Swift.String?

    public init(
        clientToken: Swift.String? = nil,
        savingsPlanId: Swift.String? = nil
    )
    {
        self.clientToken = clientToken
        self.savingsPlanId = savingsPlanId
    }
}

public struct ReturnSavingsPlanOutput: Swift.Sendable {
    /// The ID of the Savings Plan.
    public var savingsPlanId: Swift.String?

    public init(
        savingsPlanId: Swift.String? = nil
    )
    {
        self.savingsPlanId = savingsPlanId
    }
}

public struct TagResourceInput: Swift.Sendable {
    /// The Amazon Resource Name (ARN) of the resource.
    /// This member is required.
    public var resourceArn: Swift.String?
    /// One or more tags. For example, { "tags": {"key1":"value1", "key2":"value2"} }.
    /// This member is required.
    public var tags: [Swift.String: Swift.String]?

    public init(
        resourceArn: Swift.String? = nil,
        tags: [Swift.String: Swift.String]? = nil
    )
    {
        self.resourceArn = resourceArn
        self.tags = tags
    }
}

public struct TagResourceOutput: Swift.Sendable {

    public init() { }
}

public struct UntagResourceInput: Swift.Sendable {
    /// The Amazon Resource Name (ARN) of the resource.
    /// This member is required.
    public var resourceArn: Swift.String?
    /// The tag keys.
    /// This member is required.
    public var tagKeys: [Swift.String]?

    public init(
        resourceArn: Swift.String? = nil,
        tagKeys: [Swift.String]? = nil
    )
    {
        self.resourceArn = resourceArn
        self.tagKeys = tagKeys
    }
}

public struct UntagResourceOutput: Swift.Sendable {

    public init() { }
}

extension CreateSavingsPlanInput {

    static func urlPathProvider(_ value: CreateSavingsPlanInput) -> Swift.String? {
        return "/CreateSavingsPlan"
    }
}

extension DeleteQueuedSavingsPlanInput {

    static func urlPathProvider(_ value: DeleteQueuedSavingsPlanInput) -> Swift.String? {
        return "/DeleteQueuedSavingsPlan"
    }
}

extension DescribeSavingsPlanRatesInput {

    static func urlPathProvider(_ value: DescribeSavingsPlanRatesInput) -> Swift.String? {
        return "/DescribeSavingsPlanRates"
    }
}

extension DescribeSavingsPlansInput {

    static func urlPathProvider(_ value: DescribeSavingsPlansInput) -> Swift.String? {
        return "/DescribeSavingsPlans"
    }
}

extension DescribeSavingsPlansOfferingRatesInput {

    static func urlPathProvider(_ value: DescribeSavingsPlansOfferingRatesInput) -> Swift.String? {
        return "/DescribeSavingsPlansOfferingRates"
    }
}

extension DescribeSavingsPlansOfferingsInput {

    static func urlPathProvider(_ value: DescribeSavingsPlansOfferingsInput) -> Swift.String? {
        return "/DescribeSavingsPlansOfferings"
    }
}

extension ListTagsForResourceInput {

    static func urlPathProvider(_ value: ListTagsForResourceInput) -> Swift.String? {
        return "/ListTagsForResource"
    }
}

extension ReturnSavingsPlanInput {

    static func urlPathProvider(_ value: ReturnSavingsPlanInput) -> Swift.String? {
        return "/ReturnSavingsPlan"
    }
}

extension TagResourceInput {

    static func urlPathProvider(_ value: TagResourceInput) -> Swift.String? {
        return "/TagResource"
    }
}

extension UntagResourceInput {

    static func urlPathProvider(_ value: UntagResourceInput) -> Swift.String? {
        return "/UntagResource"
    }
}

extension CreateSavingsPlanInput {

    static func write(value: CreateSavingsPlanInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["clientToken"].write(value.clientToken)
        try writer["commitment"].write(value.commitment)
        try writer["purchaseTime"].writeTimestamp(value.purchaseTime, format: SmithyTimestamps.TimestampFormat.epochSeconds)
        try writer["savingsPlanOfferingId"].write(value.savingsPlanOfferingId)
        try writer["tags"].writeMap(value.tags, valueWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), keyNodeInfo: "key", valueNodeInfo: "value", isFlattened: false)
        try writer["upfrontPaymentAmount"].write(value.upfrontPaymentAmount)
    }
}

extension DeleteQueuedSavingsPlanInput {

    static func write(value: DeleteQueuedSavingsPlanInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["savingsPlanId"].write(value.savingsPlanId)
    }
}

extension DescribeSavingsPlanRatesInput {

    static func write(value: DescribeSavingsPlanRatesInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["filters"].writeList(value.filters, memberWritingClosure: SavingsplansClientTypes.SavingsPlanRateFilter.write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["maxResults"].write(value.maxResults)
        try writer["nextToken"].write(value.nextToken)
        try writer["savingsPlanId"].write(value.savingsPlanId)
    }
}

extension DescribeSavingsPlansInput {

    static func write(value: DescribeSavingsPlansInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["filters"].writeList(value.filters, memberWritingClosure: SavingsplansClientTypes.SavingsPlanFilter.write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["maxResults"].write(value.maxResults)
        try writer["nextToken"].write(value.nextToken)
        try writer["savingsPlanArns"].writeList(value.savingsPlanArns, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["savingsPlanIds"].writeList(value.savingsPlanIds, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["states"].writeList(value.states, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanState>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension DescribeSavingsPlansOfferingRatesInput {

    static func write(value: DescribeSavingsPlansOfferingRatesInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["filters"].writeList(value.filters, memberWritingClosure: SavingsplansClientTypes.SavingsPlanOfferingRateFilterElement.write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["maxResults"].write(value.maxResults)
        try writer["nextToken"].write(value.nextToken)
        try writer["operations"].writeList(value.operations, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["products"].writeList(value.products, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanProductType>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["savingsPlanOfferingIds"].writeList(value.savingsPlanOfferingIds, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["savingsPlanPaymentOptions"].writeList(value.savingsPlanPaymentOptions, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanPaymentOption>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["savingsPlanTypes"].writeList(value.savingsPlanTypes, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanType>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["serviceCodes"].writeList(value.serviceCodes, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanRateServiceCode>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["usageTypes"].writeList(value.usageTypes, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension DescribeSavingsPlansOfferingsInput {

    static func write(value: DescribeSavingsPlansOfferingsInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["currencies"].writeList(value.currencies, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.CurrencyCode>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["descriptions"].writeList(value.descriptions, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["durations"].writeList(value.durations, memberWritingClosure: SmithyReadWrite.WritingClosures.writeInt(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["filters"].writeList(value.filters, memberWritingClosure: SavingsplansClientTypes.SavingsPlanOfferingFilterElement.write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["maxResults"].write(value.maxResults)
        try writer["nextToken"].write(value.nextToken)
        try writer["offeringIds"].writeList(value.offeringIds, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["operations"].writeList(value.operations, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["paymentOptions"].writeList(value.paymentOptions, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanPaymentOption>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["planTypes"].writeList(value.planTypes, memberWritingClosure: SmithyReadWrite.WritingClosureBox<SavingsplansClientTypes.SavingsPlanType>().write(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["productType"].write(value.productType)
        try writer["serviceCodes"].writeList(value.serviceCodes, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
        try writer["usageTypes"].writeList(value.usageTypes, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension ListTagsForResourceInput {

    static func write(value: ListTagsForResourceInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["resourceArn"].write(value.resourceArn)
    }
}

extension ReturnSavingsPlanInput {

    static func write(value: ReturnSavingsPlanInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["clientToken"].write(value.clientToken)
        try writer["savingsPlanId"].write(value.savingsPlanId)
    }
}

extension TagResourceInput {

    static func write(value: TagResourceInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["resourceArn"].write(value.resourceArn)
        try writer["tags"].writeMap(value.tags, valueWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), keyNodeInfo: "key", valueNodeInfo: "value", isFlattened: false)
    }
}

extension UntagResourceInput {

    static func write(value: UntagResourceInput?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["resourceArn"].write(value.resourceArn)
        try writer["tagKeys"].writeList(value.tagKeys, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension CreateSavingsPlanOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> CreateSavingsPlanOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = CreateSavingsPlanOutput()
        value.savingsPlanId = try reader["savingsPlanId"].readIfPresent()
        return value
    }
}

extension DeleteQueuedSavingsPlanOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> DeleteQueuedSavingsPlanOutput {
        return DeleteQueuedSavingsPlanOutput()
    }
}

extension DescribeSavingsPlanRatesOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> DescribeSavingsPlanRatesOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = DescribeSavingsPlanRatesOutput()
        value.nextToken = try reader["nextToken"].readIfPresent()
        value.savingsPlanId = try reader["savingsPlanId"].readIfPresent()
        value.searchResults = try reader["searchResults"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanRate.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension DescribeSavingsPlansOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> DescribeSavingsPlansOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = DescribeSavingsPlansOutput()
        value.nextToken = try reader["nextToken"].readIfPresent()
        value.savingsPlans = try reader["savingsPlans"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlan.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension DescribeSavingsPlansOfferingRatesOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> DescribeSavingsPlansOfferingRatesOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = DescribeSavingsPlansOfferingRatesOutput()
        value.nextToken = try reader["nextToken"].readIfPresent()
        value.searchResults = try reader["searchResults"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanOfferingRate.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension DescribeSavingsPlansOfferingsOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> DescribeSavingsPlansOfferingsOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = DescribeSavingsPlansOfferingsOutput()
        value.nextToken = try reader["nextToken"].readIfPresent()
        value.searchResults = try reader["searchResults"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanOffering.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension ListTagsForResourceOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> ListTagsForResourceOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = ListTagsForResourceOutput()
        value.tags = try reader["tags"].readMapIfPresent(valueReadingClosure: SmithyReadWrite.ReadingClosures.readString(from:), keyNodeInfo: "key", valueNodeInfo: "value", isFlattened: false)
        return value
    }
}

extension ReturnSavingsPlanOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> ReturnSavingsPlanOutput {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let reader = responseReader
        var value = ReturnSavingsPlanOutput()
        value.savingsPlanId = try reader["savingsPlanId"].readIfPresent()
        return value
    }
}

extension TagResourceOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> TagResourceOutput {
        return TagResourceOutput()
    }
}

extension UntagResourceOutput {

    static func httpOutput(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> UntagResourceOutput {
        return UntagResourceOutput()
    }
}

enum CreateSavingsPlanOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ServiceQuotaExceededException": return try ServiceQuotaExceededException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum DeleteQueuedSavingsPlanOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ServiceQuotaExceededException": return try ServiceQuotaExceededException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum DescribeSavingsPlanRatesOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum DescribeSavingsPlansOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum DescribeSavingsPlansOfferingRatesOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum DescribeSavingsPlansOfferingsOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum ListTagsForResourceOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum ReturnSavingsPlanOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ServiceQuotaExceededException": return try ServiceQuotaExceededException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum TagResourceOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ServiceQuotaExceededException": return try ServiceQuotaExceededException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

enum UntagResourceOutputError {

    static func httpError(from httpResponse: SmithyHTTPAPI.HTTPResponse) async throws -> Swift.Error {
        let data = try await httpResponse.data()
        let responseReader = try SmithyJSON.Reader.from(data: data)
        let baseError = try AWSClientRuntime.RestJSONError(httpResponse: httpResponse, responseReader: responseReader, noErrorWrapping: false)
        if let error = baseError.customError() { return error }
        switch baseError.code {
            case "InternalServerException": return try InternalServerException.makeError(baseError: baseError)
            case "ResourceNotFoundException": return try ResourceNotFoundException.makeError(baseError: baseError)
            case "ValidationException": return try ValidationException.makeError(baseError: baseError)
            default: return try AWSClientRuntime.UnknownAWSHTTPServiceError.makeError(baseError: baseError)
        }
    }
}

extension ServiceQuotaExceededException {

    static func makeError(baseError: AWSClientRuntime.RestJSONError) throws -> ServiceQuotaExceededException {
        let reader = baseError.errorBodyReader
        var value = ServiceQuotaExceededException()
        value.properties.message = try reader["message"].readIfPresent() ?? ""
        value.httpResponse = baseError.httpResponse
        value.requestID = baseError.requestID
        value.message = baseError.message
        return value
    }
}

extension InternalServerException {

    static func makeError(baseError: AWSClientRuntime.RestJSONError) throws -> InternalServerException {
        let reader = baseError.errorBodyReader
        var value = InternalServerException()
        value.properties.message = try reader["message"].readIfPresent() ?? ""
        value.httpResponse = baseError.httpResponse
        value.requestID = baseError.requestID
        value.message = baseError.message
        return value
    }
}

extension ResourceNotFoundException {

    static func makeError(baseError: AWSClientRuntime.RestJSONError) throws -> ResourceNotFoundException {
        let reader = baseError.errorBodyReader
        var value = ResourceNotFoundException()
        value.properties.message = try reader["message"].readIfPresent() ?? ""
        value.httpResponse = baseError.httpResponse
        value.requestID = baseError.requestID
        value.message = baseError.message
        return value
    }
}

extension ValidationException {

    static func makeError(baseError: AWSClientRuntime.RestJSONError) throws -> ValidationException {
        let reader = baseError.errorBodyReader
        var value = ValidationException()
        value.properties.message = try reader["message"].readIfPresent() ?? ""
        value.httpResponse = baseError.httpResponse
        value.requestID = baseError.requestID
        value.message = baseError.message
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanRate {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanRate {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanRate()
        value.rate = try reader["rate"].readIfPresent()
        value.currency = try reader["currency"].readIfPresent()
        value.unit = try reader["unit"].readIfPresent()
        value.productType = try reader["productType"].readIfPresent()
        value.serviceCode = try reader["serviceCode"].readIfPresent()
        value.usageType = try reader["usageType"].readIfPresent()
        value.operation = try reader["operation"].readIfPresent()
        value.properties = try reader["properties"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanRateProperty.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanRateProperty {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanRateProperty {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanRateProperty()
        value.name = try reader["name"].readIfPresent()
        value.value = try reader["value"].readIfPresent()
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlan {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlan {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlan()
        value.offeringId = try reader["offeringId"].readIfPresent()
        value.savingsPlanId = try reader["savingsPlanId"].readIfPresent()
        value.savingsPlanArn = try reader["savingsPlanArn"].readIfPresent()
        value.description = try reader["description"].readIfPresent()
        value.start = try reader["start"].readIfPresent()
        value.end = try reader["end"].readIfPresent()
        value.state = try reader["state"].readIfPresent()
        value.region = try reader["region"].readIfPresent()
        value.ec2InstanceFamily = try reader["ec2InstanceFamily"].readIfPresent()
        value.savingsPlanType = try reader["savingsPlanType"].readIfPresent()
        value.paymentOption = try reader["paymentOption"].readIfPresent()
        value.productTypes = try reader["productTypes"].readListIfPresent(memberReadingClosure: SmithyReadWrite.ReadingClosureBox<SavingsplansClientTypes.SavingsPlanProductType>().read(from:), memberNodeInfo: "member", isFlattened: false)
        value.currency = try reader["currency"].readIfPresent()
        value.commitment = try reader["commitment"].readIfPresent()
        value.upfrontPaymentAmount = try reader["upfrontPaymentAmount"].readIfPresent()
        value.recurringPaymentAmount = try reader["recurringPaymentAmount"].readIfPresent()
        value.termDurationInSeconds = try reader["termDurationInSeconds"].readIfPresent() ?? 0
        value.tags = try reader["tags"].readMapIfPresent(valueReadingClosure: SmithyReadWrite.ReadingClosures.readString(from:), keyNodeInfo: "key", valueNodeInfo: "value", isFlattened: false)
        value.returnableUntil = try reader["returnableUntil"].readIfPresent()
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanOfferingRate {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanOfferingRate {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanOfferingRate()
        value.savingsPlanOffering = try reader["savingsPlanOffering"].readIfPresent(with: SavingsplansClientTypes.ParentSavingsPlanOffering.read(from:))
        value.rate = try reader["rate"].readIfPresent()
        value.unit = try reader["unit"].readIfPresent()
        value.productType = try reader["productType"].readIfPresent()
        value.serviceCode = try reader["serviceCode"].readIfPresent()
        value.usageType = try reader["usageType"].readIfPresent()
        value.operation = try reader["operation"].readIfPresent()
        value.properties = try reader["properties"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanOfferingRateProperty.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanOfferingRateProperty {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanOfferingRateProperty {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanOfferingRateProperty()
        value.name = try reader["name"].readIfPresent()
        value.value = try reader["value"].readIfPresent()
        return value
    }
}

extension SavingsplansClientTypes.ParentSavingsPlanOffering {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.ParentSavingsPlanOffering {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.ParentSavingsPlanOffering()
        value.offeringId = try reader["offeringId"].readIfPresent()
        value.paymentOption = try reader["paymentOption"].readIfPresent()
        value.planType = try reader["planType"].readIfPresent()
        value.durationSeconds = try reader["durationSeconds"].readIfPresent() ?? 0
        value.currency = try reader["currency"].readIfPresent()
        value.planDescription = try reader["planDescription"].readIfPresent()
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanOffering {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanOffering {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanOffering()
        value.offeringId = try reader["offeringId"].readIfPresent()
        value.productTypes = try reader["productTypes"].readListIfPresent(memberReadingClosure: SmithyReadWrite.ReadingClosureBox<SavingsplansClientTypes.SavingsPlanProductType>().read(from:), memberNodeInfo: "member", isFlattened: false)
        value.planType = try reader["planType"].readIfPresent()
        value.description = try reader["description"].readIfPresent()
        value.paymentOption = try reader["paymentOption"].readIfPresent()
        value.durationSeconds = try reader["durationSeconds"].readIfPresent() ?? 0
        value.currency = try reader["currency"].readIfPresent()
        value.serviceCode = try reader["serviceCode"].readIfPresent()
        value.usageType = try reader["usageType"].readIfPresent()
        value.operation = try reader["operation"].readIfPresent()
        value.properties = try reader["properties"].readListIfPresent(memberReadingClosure: SavingsplansClientTypes.SavingsPlanOfferingProperty.read(from:), memberNodeInfo: "member", isFlattened: false)
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanOfferingProperty {

    static func read(from reader: SmithyJSON.Reader) throws -> SavingsplansClientTypes.SavingsPlanOfferingProperty {
        guard reader.hasContent else { throw SmithyReadWrite.ReaderError.requiredValueNotPresent }
        var value = SavingsplansClientTypes.SavingsPlanOfferingProperty()
        value.name = try reader["name"].readIfPresent()
        value.value = try reader["value"].readIfPresent()
        return value
    }
}

extension SavingsplansClientTypes.SavingsPlanRateFilter {

    static func write(value: SavingsplansClientTypes.SavingsPlanRateFilter?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["name"].write(value.name)
        try writer["values"].writeList(value.values, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension SavingsplansClientTypes.SavingsPlanFilter {

    static func write(value: SavingsplansClientTypes.SavingsPlanFilter?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["name"].write(value.name)
        try writer["values"].writeList(value.values, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension SavingsplansClientTypes.SavingsPlanOfferingRateFilterElement {

    static func write(value: SavingsplansClientTypes.SavingsPlanOfferingRateFilterElement?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["name"].write(value.name)
        try writer["values"].writeList(value.values, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

extension SavingsplansClientTypes.SavingsPlanOfferingFilterElement {

    static func write(value: SavingsplansClientTypes.SavingsPlanOfferingFilterElement?, to writer: SmithyJSON.Writer) throws {
        guard let value else { return }
        try writer["name"].write(value.name)
        try writer["values"].writeList(value.values, memberWritingClosure: SmithyReadWrite.WritingClosures.writeString(value:to:), memberNodeInfo: "member", isFlattened: false)
    }
}

public enum SavingsplansClientTypes {}
