load '../../build-support/dependencies.rb'

platform :ios, '12.0'
use_frameworks!

include_build_tools!

target 'AWSPinpointAnalyticsPlugin' do
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    pod "AWSPinpoint", $OPTIMISTIC_AWS_SDK_VERSION
end

target "HostApp" do
    use_frameworks!
    include_test_utilities!

    pod 'AmplifyTestCommon', :path => '../../'
    pod 'Amplify', :path => '../../'
    pod 'AWSPluginsCore', :path => '../../'
    
    target "AWSPinpointAnalyticsPluginIntegrationTests" do
        pod 'AmplifyPlugins/AWSCognitoAuthPlugin', :path => '../../'

        inherit! :complete
    end

    target "AWSPinpointAnalyticsPluginTests" do
        inherit! :complete
    end
end
