name: 'Get the build parameters for a given platform'
inputs:
  platform:
    description: 'The name of the platform. Valid values are iOS, tvOS, watchOS and macOS'
    required: true
    type: string
  xcode_version:
    description: "The version of Xcode. Available aliases are 'latest' and 'minimum'"
    default: 'latest'
    type: string
  destination:
    description: "The destination associated with the given platform and Xcode version"
    default: ''
    type: string

outputs:
  destination:
    description: "The destination associated with the given platform and Xcode version"
    value: ${{ steps.get-destination.outputs.destination }}
  device:
      description: "The device name used in the destination"
      value: ${{ steps.get-destination.outputs.device }}
  sdk:
    description: "The SDK associated with the given platform"
    value: ${{ steps.get-sdk.outputs.sdk }}
  xcode-version:
    description: "The Xcode version to build with"
    value: ${{ steps.get-xcode-version.outputs.xcode-version }}

runs:
  using: "composite"
  steps:
    - name: Validate platform
      run: |
        INPUT_PLATFORM=${{ inputs.platform }}
        case $INPUT_PLATFORM in
          iOS|tvOS|watchOS|macOS|visionOS) ;;
          *) echo "Unsupported platform: $INPUT_PLATFORM"; exit 1 ;;
        esac
      shell: bash

    - id: get-xcode-version
      run: |
        LATEST_XCODE_VERSION=16.0.0
        MINIMUM_XCODE_VERSION=15.0.1

        INPUT_XCODE_VERSION=${{ inputs.xcode_version }}

        case $INPUT_XCODE_VERSION in
          latest)
            XCODE_VERSION=$LATEST_XCODE_VERSION ;;
          minimum)
            XCODE_VERSION=$MINIMUM_XCODE_VERSION ;;
          *)
            XCODE_VERSION=$INPUT_XCODE_VERSION ;;
        esac
        echo "xcode-version=$XCODE_VERSION" >> $GITHUB_OUTPUT

      shell: bash

    - id: get-destination
      run: |
        INPUT_PLATFORM=${{ inputs.platform }}
        INPUT_DESTINATION='${{ inputs.destination }}'
        INPUT_XCODE_VERSION=${{ inputs.xcode_version }}

        case $INPUT_PLATFORM/$INPUT_XCODE_VERSION in
          iOS/latest) 
            DEVICE="iPhone 16"
            OS_VERSION="18.0"
            ;;
          iOS/*)
            DEVICE="iPhone 14"
            OS_VERSION="17.0.1"
            ;;
          tvOS/latest)
            DEVICE="Apple TV 4K (3rd generation)"
            OS_VERSION="18.0"
            ;;
          tvOS/*)
            DEVICE="Apple TV 4K (3rd generation)"
            OS_VERSION="17.0"
            ;;
          watchOS/latest)
            DEVICE="Apple Watch Series 10 (46mm)"
            OS_VERSION="11.0"
            ;;
          watchOS/*)
            DEVICE="Apple Watch Series 8 (45mm)"
            OS_VERSION="10.0"
            ;;
          visionOS/latest)
            DEVICE="Apple Vision Pro"
            OS_VERSION="2.0"
            ;;
          visionOS/*)
            DEVICE="Apple Vision Pro"
            OS_VERSION="1.0"
            ;;
        esac

        DESTINATION_MAPPING="{
          \"iOS\": \"platform=iOS Simulator,name=$DEVICE,OS=$OS_VERSION\",
          \"tvOS\": \"platform=tvOS Simulator,name=$DEVICE,OS=$OS_VERSION\",
          \"watchOS\": \"platform=watchOS Simulator,name=$DEVICE,OS=$OS_VERSION\",
          \"visionOS\": \"platform=visionOS Simulator,name=$DEVICE,OS=$OS_VERSION\",
          \"macOS\": \"platform=macOS,arch=arm64\"
        }"

        if [ -z "$INPUT_DESTINATION" ]; then
          DESTINATION=$(echo $DESTINATION_MAPPING | jq -r ".$INPUT_PLATFORM")
        else
          DESTINATION=$INPUT_DESTINATION
        fi

        if [ -z "$DESTINATION" ]; then
          echo "No available destination to build for"
          exit 1
        fi
        echo "destination=$DESTINATION" >> $GITHUB_OUTPUT
        echo "device=$DEVICE" >> $GITHUB_OUTPUT
      shell: bash

    - id: get-sdk
      run: |
        INPUT_PLATFORM=${{ inputs.platform }}
        SDK_MAPPING='{
          "iOS": "iphonesimulator",
          "tvOS": "appletvsimulator",
          "watchOS": "watchsimulator",
          "visionOS": "xrsimulator",
          "macOS": "macosx"
        }'
        echo "sdk=$(echo $SDK_MAPPING | jq -r .$INPUT_PLATFORM)" >> $GITHUB_OUTPUT
      shell: bash