name: Integration Tests | Logging
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  logging-integration-tests:
    name: Logging Integration Tests
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSCloudWatchLoggingPluginIntegrationTests", "tvOS": "AWSCloudWatchLoggingPluginIntegrationTests", "watchOS": "AWSCloudWatchLoggingPluginIntegrationTestsWatch"}'
      project_path: ./AmplifyPlugins/Logging/Tests/AWSCloudWatchLoggingPluginHostApp
      resource_subfolder: logging
    secrets: inherit
