name: Integration Tests | API - GraphQL IAM
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  api-graphql-iam-tests:
    name: API Integration Tests | GraphQL IAM
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSAPIPluginGraphQLIAMTests", "tvOS": "AWSAPIPluginGraphQLIAMTests", "watchOS": "AWSAPIPluginGraphQLIAMTestsWatch"}'
      project_path: ./AmplifyPlugins/API/Tests/APIHostApp
      resource_subfolder: api
    secrets: inherit
