name: Integration Tests | Predictions
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  predictions-integration-tests:
    name: Predictions Integration Tests
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSPredictionsPluginIntegrationTests", "tvOS": "AWSPredictionsPluginIntegrationTests", "watchOS": "AWSPredictionsPluginIntegrationTestsWatch"}'
      project_path: ./AmplifyPlugins/Predictions/Tests/PredictionsHostApp
      resource_subfolder: predictions
    secrets: inherit
