name: Integration Tests | DataStore - Auth IAM
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  datastore-integration-auth-iam-tests:
    name: DataStore Integration Tests | Auth IAM
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSDataStorePluginAuthIAMTests", "tvOS": "AWSDataStorePluginAuthIAMTests", "watchOS": "AWSDataStorePluginAuthIAMTestsWatch"}'
      project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
      resource_subfolder: datastore
    secrets: inherit
