name: Integration Tests | DataStore - TransformerV2
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  datastore-integration-v2-tests:
    name: DataStore Integration Tests | Transformer V2
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSDataStorePluginV2Tests", "tvOS": "AWSDataStorePluginV2Tests", "watchOS": "AWSDataStorePluginV2TestsWatch"}'
      project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
      resource_subfolder: datastore
    secrets: inherit
