name: Integration Tests | DataStore - CPK
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  datastore-integration-cpk-tests:
    name: DataStore Integration Tests | CPK
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSDataStorePluginCPKTests", "tvOS": "AWSDataStorePluginCPKTests", "watchOS": "AWSDataStorePluginCPKTestsWatch"}'
      project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
      resource_subfolder: datastore
    secrets: inherit
