name: Integration Tests | DataStore - Multi Auth
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  datastore-integration-multi-auth-tests:
    name: DataStore Integration Tests | Multi Auth
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSDataStorePluginMultiAuthTests", "tvOS": "AWSDataStorePluginMultiAuthTests", "watchOS": "AWSDataStorePluginMultiAuthTestsWatch"}'
      project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
      resource_subfolder: datastore
    secrets: inherit
