name: Integration Tests | API - GraphQL Lambda
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  api-graphql-lambda-auth-tests:
    name: API Integration Tests | GraphQL Lambda
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSAPIPluginGraphQLLambdaAuthTests", "tvOS": "AWSAPIPluginGraphQLLambdaAuthTests", "watchOS": "AWSAPIPluginGraphQLLambdaAuthTestsWatch"}'
      project_path: ./AmplifyPlugins/API/Tests/APIHostApp
      resource_subfolder: api
    secrets: inherit
