name: Integration Tests | DataStore - Lazy Load
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  datastore-integration-lazy-load-tests:
    name: DataStore Integration Tests | Lazy Load
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, tvOS, watchOS]
        exclude:
          - platform: ${{ github.event.inputs.ios == 'false' && 'iOS' || 'Dummy' }}
          - platform: ${{ github.event.inputs.tvos == 'false' && 'tvOS' || 'Dummy' }}
          - platform: ${{ github.event.inputs.watchos == 'false' && 'watchOS' || 'Dummy' }}
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      scheme: ${{ matrix.platform == 'watchOS' && 'AWSDataStorePluginLazyLoadTestsWatch' || 'AWSDataStorePluginLazyLoadTests' }}
      platform: ${{ matrix.platform }}
      build_cache_key: AWSDataStorePlugin-${{ matrix.platform }}-latest-build-main
      project_path: ./AmplifyPlugins/DataStore/Tests/DataStoreHostApp
      xcode_version: '14.3'
      resource_subfolder: datastore
      timeout-minutes: 120
    secrets: inherit
