name: Integration Tests | Analytics
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
  workflow_call:

permissions:
    id-token: write
    contents: read

jobs:
  analytics-integration-tests:
    name: Analytics Integration Tests
    uses: ./.github/workflows/run_integration_tests.yml
    with:
      schemes: '{"iOS": "AWSPinpointAnalyticsPluginIntegrationTests", "tvOS": "AWSPinpointAnalyticsPluginIntegrationTests", "watchOS": "AWSPinpointAnalyticsPluginIntegrationTestsWatch"}'
      project_path: ./AmplifyPlugins/Analytics/Tests/AnalyticsHostApp
      resource_subfolder: analytics
    secrets: inherit
