# Merges Release PRs 
name: Merge Release PR

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - release

permissions:
  contents: write

jobs:
  check:
    name: Merge PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Validate PR and Merge
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
          TITLE: ${{ github.event.pull_request.title }}
          PR: ${{ github.event.pull_request.number }}
          EXPECTED_HEAD: "main"
          EXPECTED_TITLE: "chore: kickoff release"
        if: ${{ github.event.review.state == 'approved' }} && ${{ env.HEAD_REF == env.EXPECTED_HEAD }} && ${{ env.TITLE == env.EXPECTED_TITLE }}
        run: "gh pr merge $PR --merge --subject 'chore: kickoff release' --body ''"
