name: Unit Tests | Predictions
on:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  predictions-unit-tests:
    uses: ./.github/workflows/run_xcodebuild_test_platforms.yml
    with:
      scheme: AWSPredictionsPlugin

  coreml-predictions-unit-tests:
    uses: ./.github/workflows/run_xcodebuild_test_platforms.yml
    with:
      scheme: CoreMLPredictionsPlugin
