name: Unit Tests | DataStore
on:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  datastore-unit-tests:
    uses: ./.github/workflows/run_xcodebuild_test_platforms.yml
    with:
      scheme: AWSDataStorePlugin
