name: Unit Tests | API
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      macos:
        description: '💻 macOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean
      visionos:
        description: 'ᯅ visionOS'
        required: true
        default: true
        type: boolean 

permissions:
    contents: read

jobs:
  api-unit-tests:
    name: ${{ matrix.platform }} Unit Tests
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, macOS, tvOS, watchOS, visionOS]
        exclude:
          - platform: ${{ github.event.inputs.ios == 'false' && 'iOS' || 'None' }}
          - platform: ${{ github.event.inputs.macos == 'false' && 'macOS' || 'None' }}
          - platform: ${{ github.event.inputs.tvos == 'false' && 'tvOS' || 'None' }}
          - platform: ${{ github.event.inputs.watchos == 'false' && 'watchOS' || 'None' }}
          - platform: ${{ github.event.inputs.visionos == 'false' && 'visionOS' || 'None' }}
    uses: ./.github/workflows/run_platform_all_schemes.yml
    with:
      platform: ${{ matrix.platform }}
      schemes: '["AWSAPIPlugin"]'
