name: Unit Tests | DataStore
on:
  workflow_dispatch:
    inputs:
      ios:
        description: '📱 iOS'
        required: true
        default: true
        type: boolean
      macos:
        description: '💻 macOS'
        required: true
        default: true
        type: boolean
      tvos:
        description: '📺 tvOS'
        required: true
        default: true
        type: boolean
      watchos:
        description: '⌚️ watchOS'
        required: true
        default: true
        type: boolean

permissions:
    contents: read

jobs:
  datastore-unit-tests:
    uses: ./.github/workflows/run_unit_tests_platforms.yml
    with:
      scheme: AWSDataStorePlugin
