name: Unit Tests | Geo
on:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  geo-unit-tests:
    uses: ./.github/workflows/run_unit_tests_platforms.yml
    with:
      scheme: AWSLocationGeoPlugin
